/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookRouteImport } from './routes/book'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoreRouteImport } from './routes/store'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TransmissionsRouteImport } from './routes/transmissions'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as LabSlugRouteImport } from './routes/lab.$slug'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerAnalyticsRouteImport } from './routes/owner.analytics'
import { Route as OwnerBotsRouteImport } from './routes/owner.bots'
import { Route as OwnerInboxRouteImport } from './routes/owner.inbox'
import { Route as OwnerJournalRouteImport } from './routes/owner.journal'
import { Route as OwnerPromosRouteImport } from './routes/owner.promos'
import { Route as OwnerReviewsRouteImport } from './routes/owner.reviews'
import { Route as OwnerRunbookRouteImport } from './routes/owner.runbook'
import { Route as OwnerSeoRouteImport } from './routes/owner.seo'
import { Route as OwnerServicesRouteImport } from './routes/owner.services'
import { Route as OwnerSiteRouteImport } from './routes/owner.site'
import { Route as OwnerStoreRouteImport } from './routes/owner.store'
import { Route as OwnerWorkRouteImport } from './routes/owner.work'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TransmissionsRoute = TransmissionsRouteImport.update({
  id: '/transmissions',
  path: '/transmissions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRoute,
} as any)
const LabSlugRoute = LabSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LabRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAnalyticsRoute = OwnerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBotsRoute = OwnerBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerInboxRoute = OwnerInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerJournalRoute = OwnerJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPromosRoute = OwnerPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReviewsRoute = OwnerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRunbookRoute = OwnerRunbookRouteImport.update({
  id: '/runbook',
  path: '/runbook',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSeoRoute = OwnerSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerServicesRoute = OwnerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSiteRoute = OwnerSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerStoreRoute = OwnerStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerWorkRoute = OwnerWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => OwnerRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/owner': typeof OwnerRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRouteWithChildren
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/transmissions': typeof TransmissionsRoute
  '/work': typeof WorkRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bots': typeof OwnerBotsRoute
  '/owner/inbox': typeof OwnerInboxRoute
  '/owner/journal': typeof OwnerJournalRoute
  '/owner/promos': typeof OwnerPromosRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/runbook': typeof OwnerRunbookRoute
  '/owner/seo': typeof OwnerSeoRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/site': typeof OwnerSiteRoute
  '/owner/store': typeof OwnerStoreRoute
  '/owner/work': typeof OwnerWorkRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/lab/': typeof LabIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/store/': typeof StoreIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/transmissions': typeof TransmissionsRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bots': typeof OwnerBotsRoute
  '/owner/inbox': typeof OwnerInboxRoute
  '/owner/journal': typeof OwnerJournalRoute
  '/owner/promos': typeof OwnerPromosRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/runbook': typeof OwnerRunbookRoute
  '/owner/seo': typeof OwnerSeoRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/site': typeof OwnerSiteRoute
  '/owner/store': typeof OwnerStoreRoute
  '/owner/work': typeof OwnerWorkRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/journal': typeof JournalIndexRoute
  '/lab': typeof LabIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/services': typeof ServicesIndexRoute
  '/store': typeof StoreIndexRoute
  '/work': typeof WorkIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/owner': typeof OwnerRouteWithChildren
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRouteWithChildren
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/transmissions': typeof TransmissionsRoute
  '/work': typeof WorkRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/lab/$slug': typeof LabSlugRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bots': typeof OwnerBotsRoute
  '/owner/inbox': typeof OwnerInboxRoute
  '/owner/journal': typeof OwnerJournalRoute
  '/owner/promos': typeof OwnerPromosRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/runbook': typeof OwnerRunbookRoute
  '/owner/seo': typeof OwnerSeoRoute
  '/owner/services': typeof OwnerServicesRoute
  '/owner/site': typeof OwnerSiteRoute
  '/owner/store': typeof OwnerStoreRoute
  '/owner/work': typeof OwnerWorkRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/lab/': typeof LabIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/store/': typeof StoreIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/book'
    | '/cart'
    | '/case-studies'
    | '/contact'
    | '/faq'
    | '/journal'
    | '/lab'
    | '/llms.txt'
    | '/login'
    | '/manifest.webmanifest'
    | '/owner'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/reviews'
    | '/robots.txt'
    | '/rss.xml'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/studio'
    | '/terms'
    | '/transmissions'
    | '/work'
    | '/api/health'
    | '/blog/$slug'
    | '/journal/$slug'
    | '/lab/$slug'
    | '/owner/analytics'
    | '/owner/bots'
    | '/owner/inbox'
    | '/owner/journal'
    | '/owner/promos'
    | '/owner/reviews'
    | '/owner/runbook'
    | '/owner/seo'
    | '/owner/services'
    | '/owner/site'
    | '/owner/store'
    | '/owner/work'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/store/$slug'
    | '/work/$slug'
    | '/journal/'
    | '/lab/'
    | '/owner/'
    | '/services/'
    | '/store/'
    | '/work/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/book'
    | '/cart'
    | '/case-studies'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/login'
    | '/manifest.webmanifest'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/reviews'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/transmissions'
    | '/api/health'
    | '/blog/$slug'
    | '/journal/$slug'
    | '/lab/$slug'
    | '/owner/analytics'
    | '/owner/bots'
    | '/owner/inbox'
    | '/owner/journal'
    | '/owner/promos'
    | '/owner/reviews'
    | '/owner/runbook'
    | '/owner/seo'
    | '/owner/services'
    | '/owner/site'
    | '/owner/store'
    | '/owner/work'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/store/$slug'
    | '/work/$slug'
    | '/journal'
    | '/lab'
    | '/owner'
    | '/services'
    | '/store'
    | '/work'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/book'
    | '/cart'
    | '/case-studies'
    | '/contact'
    | '/faq'
    | '/journal'
    | '/lab'
    | '/llms.txt'
    | '/login'
    | '/manifest.webmanifest'
    | '/owner'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/reviews'
    | '/robots.txt'
    | '/rss.xml'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/studio'
    | '/terms'
    | '/transmissions'
    | '/work'
    | '/api/health'
    | '/blog/$slug'
    | '/journal/$slug'
    | '/lab/$slug'
    | '/owner/analytics'
    | '/owner/bots'
    | '/owner/inbox'
    | '/owner/journal'
    | '/owner/promos'
    | '/owner/reviews'
    | '/owner/runbook'
    | '/owner/seo'
    | '/owner/services'
    | '/owner/site'
    | '/owner/store'
    | '/owner/work'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/store/$slug'
    | '/work/$slug'
    | '/journal/'
    | '/lab/'
    | '/owner/'
    | '/services/'
    | '/store/'
    | '/work/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookRoute: typeof BookRoute
  CartRoute: typeof CartRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  JournalRoute: typeof JournalRouteWithChildren
  LabRoute: typeof LabRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ReviewsRoute: typeof ReviewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRouteWithChildren
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  TransmissionsRoute: typeof TransmissionsRoute
  WorkRoute: typeof WorkRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmissions': {
      id: '/transmissions'
      path: '/transmissions'
      fullPath: '/transmissions'
      preLoaderRoute: typeof TransmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/$slug': {
      id: '/lab/$slug'
      path: '/$slug'
      fullPath: '/lab/$slug'
      preLoaderRoute: typeof LabSlugRouteImport
      parentRoute: typeof LabRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/analytics': {
      id: '/owner/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAnalyticsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/bots': {
      id: '/owner/bots'
      path: '/bots'
      fullPath: '/owner/bots'
      preLoaderRoute: typeof OwnerBotsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/inbox': {
      id: '/owner/inbox'
      path: '/inbox'
      fullPath: '/owner/inbox'
      preLoaderRoute: typeof OwnerInboxRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/journal': {
      id: '/owner/journal'
      path: '/journal'
      fullPath: '/owner/journal'
      preLoaderRoute: typeof OwnerJournalRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/promos': {
      id: '/owner/promos'
      path: '/promos'
      fullPath: '/owner/promos'
      preLoaderRoute: typeof OwnerPromosRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reviews': {
      id: '/owner/reviews'
      path: '/reviews'
      fullPath: '/owner/reviews'
      preLoaderRoute: typeof OwnerReviewsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/runbook': {
      id: '/owner/runbook'
      path: '/runbook'
      fullPath: '/owner/runbook'
      preLoaderRoute: typeof OwnerRunbookRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/seo': {
      id: '/owner/seo'
      path: '/seo'
      fullPath: '/owner/seo'
      preLoaderRoute: typeof OwnerSeoRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/services': {
      id: '/owner/services'
      path: '/services'
      fullPath: '/owner/services'
      preLoaderRoute: typeof OwnerServicesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/site': {
      id: '/owner/site'
      path: '/site'
      fullPath: '/owner/site'
      preLoaderRoute: typeof OwnerSiteRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/store': {
      id: '/owner/store'
      path: '/store'
      fullPath: '/owner/store'
      preLoaderRoute: typeof OwnerStoreRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/work': {
      id: '/owner/work'
      path: '/work'
      fullPath: '/owner/work'
      preLoaderRoute: typeof OwnerWorkRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface LabRouteChildren {
  LabSlugRoute: typeof LabSlugRoute
  LabIndexRoute: typeof LabIndexRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabSlugRoute: LabSlugRoute,
  LabIndexRoute: LabIndexRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

interface OwnerRouteChildren {
  OwnerAnalyticsRoute: typeof OwnerAnalyticsRoute
  OwnerBotsRoute: typeof OwnerBotsRoute
  OwnerInboxRoute: typeof OwnerInboxRoute
  OwnerJournalRoute: typeof OwnerJournalRoute
  OwnerPromosRoute: typeof OwnerPromosRoute
  OwnerReviewsRoute: typeof OwnerReviewsRoute
  OwnerRunbookRoute: typeof OwnerRunbookRoute
  OwnerSeoRoute: typeof OwnerSeoRoute
  OwnerServicesRoute: typeof OwnerServicesRoute
  OwnerSiteRoute: typeof OwnerSiteRoute
  OwnerStoreRoute: typeof OwnerStoreRoute
  OwnerWorkRoute: typeof OwnerWorkRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAnalyticsRoute: OwnerAnalyticsRoute,
  OwnerBotsRoute: OwnerBotsRoute,
  OwnerInboxRoute: OwnerInboxRoute,
  OwnerJournalRoute: OwnerJournalRoute,
  OwnerPromosRoute: OwnerPromosRoute,
  OwnerReviewsRoute: OwnerReviewsRoute,
  OwnerRunbookRoute: OwnerRunbookRoute,
  OwnerSeoRoute: OwnerSeoRoute,
  OwnerServicesRoute: OwnerServicesRoute,
  OwnerSiteRoute: OwnerSiteRoute,
  OwnerStoreRoute: OwnerStoreRoute,
  OwnerWorkRoute: OwnerWorkRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface StoreRouteChildren {
  StoreSlugRoute: typeof StoreSlugRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreSlugRoute: StoreSlugRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  BookRoute: BookRoute,
  CartRoute: CartRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  JournalRoute: JournalRouteWithChildren,
  LabRoute: LabRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  OwnerRoute: OwnerRouteWithChildren,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ReviewsRoute: ReviewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRouteWithChildren,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  TransmissionsRoute: TransmissionsRoute,
  WorkRoute: WorkRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
